version: '3'
services:
  vite-project:
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - PORT=5173
    ports:
      - '5173:5173'
networks:
  test_vite_network:
    driver: bridge
